[WIP] Feature: ZeroMQ Connector
sysco-middleware/alpakka-connectors pull request #1
Opened 2018-07-17 13:05 UTC by jeqo

Includes following shapes:

* `Source<ZMsg, NotUsed> subscribeSource`
* `Source<ZMsg, NotUsed> pullServerSource`
* `Source<ZMsg, NotUsed> pullClientSource`
* `Sink<ZMsg, NotUsed> publishSink`
* `Sink<ZMsg, NotUsed> pushServerSink`
* `Sink<ZMsg, NotUsed> pushClientSink`

2018-07-18 22:27 UTC, jeqo commented
@chromy96 I have added some initial tests for `PUB` and `SUB` types. I think this could be enough for initial versions. If looks good to you, we can merge and work on the release process.

2018-07-19 07:29 UTC, chromy96 commented on alpakka-zeromq/src/main/java/no/sysco/middleware/alpakka/zeromq/javadsl/internal/ZmqRequestStage.java
> + * Experimental
You might want to annotate it with @ApiMayChange

2018-07-19 07:47 UTC, chromy96 requested changes

2018-07-19 07:47 UTC, chromy96 commented on alpakka-zeromq/src/main/java/no/sysco/middleware/alpakka/zeromq/javadsl/Zmq.java
>      public static void main(String[] args) throws InterruptedException {
Can we move the test code outside of the Zmq class?

2018-07-19 07:47 UTC, chromy96 commented on alpakka-zeromq/src/main/java/no/sysco/middleware/alpakka/zeromq/javadsl/Zmq.java
> +public class Zmq {
I would suggest adding javadoc to explain what different methods do (might be obvious to those who understand ZeroMQ API?). e.g. explaining the difference between pullServerSource and pullClientSource.

2018-07-19 07:47 UTC, chromy96 commented on alpakka-zeromq/src/main/java/no/sysco/middleware/alpakka/zeromq/javadsl/internal/ZmqPublishStage.java
>      private final Inlet<ZMsg> inlet = Inlet.create("ZeroMQPublish.in");
Nit: Name of the inlets/outlets should be renamed throught the code to match the renaming performed on class names (using Zmq instead of ZeroMQ)

2018-07-19 07:47 UTC, chromy96 commented on alpakka-zeromq/src/main/java/no/sysco/middleware/alpakka/zeromq/javadsl/internal/ZmqPublishStage.java
>      private final Outlet<ZMsg> outlet = Outlet.create("ZeroMQPublish.out");
ZmqPublish instead of ZeroMQPublish

2018-07-19 07:47 UTC, chromy96 commented on alpakka-zeromq/src/main/java/no/sysco/middleware/alpakka/zeromq/javadsl/internal/ZmqPushStage.java
>      private final Outlet<ZMsg> outlet = Outlet.create("ZeroMQPush.out");
Inlet and outlet name

2018-07-19 07:47 UTC, chromy96 commented on alpakka-zeromq/src/main/java/no/sysco/middleware/alpakka/zeromq/javadsl/internal/ZmqRequestStage.java
>      private final Inlet<ZMsg> inlet = Inlet.create("ZeroMQPublish.in");
Inlet and outlet name

2018-07-19 07:47 UTC, chromy96 commented on alpakka-zeromq/src/main/java/no/sysco/middleware/alpakka/zeromq/javadsl/internal/ZmqSubscribeStage.java
>      private final Outlet<ZMsg> outlet = Outlet.create("ZeroMQSubscribe.out");
Outlet name

2018-07-19 07:47 UTC, chromy96 commented on alpakka-zeromq/src/main/java/no/sysco/middleware/alpakka/zeromq/javadsl/internal/ZmqPullStage.java
>      private final Outlet<ZMsg> outlet = Outlet.create("ZeroMQPull.out");
Outlet name

2018-07-19 09:37 UTC, jeqo commented
@chromy96 take a look now, I have update docs and lets, and also add missing test cases.

2018-07-19 10:44 UTC, chromy96 approved these changes

2018-07-19 11:05 UTC, merged